### ISSUE TITLE
Problem z przekierowaniem

### ISSUE THREAD

**Issue by Marucik** [Marucik/Ulatwiaczek#14]
```
def login_user(request):
    if request.user.is_authenticated:
        return redirect('main:test_lista')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('main:test_lista')
            else:
                return render(request, 'users/login.html', {
                    'loginError': True,
                })
        else:
            return render(request, 'users/login.html')
```

Mamy problem z wylogowaniem. Jeżeli usunę pierwszego if'a wylogowanie działa poprawnie, jeżeli pierwszy if jest dalej w kodzie, program nie wylogowuje użytkownika.

**Comment by xinulsw** [comment]
Powyższy kod nie zawiera niczego związanego z wylogowywaniem. Zajrzałem natomiast do pliku users/views.py i trochę jest tam namieszane. Przede wszystkim logowanie to 1 funkcja, a wylogowanie to 2, przekazywanie dodatkowych zmiennych przez GET (typu request.GET.get('logout')) niepotrzebnie komplikuje sprawę. Najlepiej stworzyć osobną funkcję do wylogowywania i generować odpowiedni odnośnik w szablonie. Przykład znajdziecie w [python101](http://python101.readthedocs.io/pl/latest/webapps/czat/index.html#wy-logowanie).

Aby uniknąć "ręcznego" obsługiwania (wy)logowania można skorzystać z django-registration zgodnie z instrukcją [Mały Bar - Użytkownicy.](http://django-maly-bar.readthedocs.io/en/latest/malybar/index.html#uzytkownicy).

**Comment by Dawiducik** [comment]
Sposób wylogowania został zmieniony, bo tylko taki nam działa (i stąd ten issue, bo nie wiadomo dlaczego poprzedni sposób nie działał), poprzednie pliki wyglądały tak: [views.py](https://github.com/Marucik/Ulatwiaczek/blob/bea0edec09449196ee8084fc127a0b9191efed33/users/views.py), [urls.py](https://github.com/Marucik/Ulatwiaczek/blob/bea0edec09449196ee8084fc127a0b9191efed33/users/urls.py) gdzie logowanie i wylogowanie były rozdzielone na 2 różne funkcje i problem w tym że przechodząc na adres `http://127.0.0.1:8000/konto/wylogowanie` funkcja logout nie działa poprawnie i nie czyści ciasteczek i sesji (a sposób z pobraniem zmiennych GET'em działa jak należy).
