### ISSUE TITLE
Zmiana SECRET_KEY i DEBUG

### ISSUE THREAD

**Issue by xinulsw** [Marucik/Ulatwiaczek#16]
Zmiany w settings.py, zwłaszcza SECRET_KEY, mają skutki uboczne. Przede wszystkim utrudniacie testowanie kodu. Podobnie działa ustawienie opcji DEBUG na False. Jeżeli rozumiecie konsekwencje, pozostaje ewentualnie uzupełnienie README.md o uwagi nt ustawienia zmiennych środowiskowych i włączanie trybu DEBUG.

**Comment by Marucik** [comment]
To jak mamy przygotować aplikację to deploy'u na [Heroku](https://www.heroku.com/)?

**Comment by Dawiducik** [comment]
Problem z plikami, po wyłaczeniu DEBUG pliki statycznie się przeciez nie wczytają a wystawianie aplikacji z włączonym debugowaniem to chyba nie najlepsze wyjście

**Comment by xinulsw** [comment]
Wasze rozwiązanie nie jest złe, jeżeli rozumiecie jego konsekwencje, tj. utrudnienie testowania aplikacji lokalnie. Tak jak napisałem, możecie dodać informację w README, że żeby przetestować aplikację, trzeba ustawić SECRET_KEY jako zmienną środowiskową i włączyć tryb debugowania. Można też uprościć, tj. wstawić w settings.py po zmiennej DEBUG kod:
`if DEBUG:
    SECRET_KEY = 'mysecretkey'
else:
    SECRET_KEY = os.environ['SECRET_KEY']`
(oczywiście poprawnie sformatowany).
Wtedy do testowania wystarczy ustawić zmienną DEBUG na True.

Można też przywrócić ustawienia oryginalne, a konfigurację dla HEROKU umieścić w pliku [app.json](https://github.com/koduj-z-klasa/malybar/blob/master/app.json) (podlinkowałem przykład z naszego przykładowego projektu). Możecie też popatrzeć na [dokumentację Heroku](https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api).

Wybierzcie rozwiązanie, które wydaje wam się w tym momencie najmniej skomplikowane i funkcjonalne.
Byle działało i byle użytkownik wiedział, co ma zrobić, żeby przetestować waszą aplikację.

**Comment by Marucik** [comment]
Wszystko jasne. Zaraz się tym zajmiemy. Zamykam.
