### ISSUE TITLE
Problem z aplikacją

### ISSUE THREAD

**Issue by Marucik** [Marucik/Ulatwiaczek#17]
Mamy kolejny problem. Ustawiłem aplikację pod wypuszczenie na Heroku korzystając z kilku instrukcji( wszystkie były niejasne albo mieszały różne elementy, trochę się poddenerwowałem i stąd głupie nazwy commit'ów.. Przepraszam 😀). Aplikacja przechodzi deploy, logi nie wskazują na żadne błędy a pomimo tego po wejściu na adres zostaje zwrócony błąd http 500. W czym jest problem?

**Comment by xinulsw** [comment]
W requirements.txt jest wiele niepotrzebnych rzeczy. Ustawienia w ulatwiaczek/settings.py są niedobre. Sugeruję, żebyście skopiowali pliki Procfile, app.json, requirements.txt z projektu [Mały Bar](https://github.com/koduj-z-klasa/malybar) i zrobili podobne ustawienia jak w pliku [malybar/settings.py](https://github.com/koduj-z-klasa/malybar/blob/master/malybar/malybar/settings.py). Zwróćcie uwagę na kod w liniach: 26-38, 89-110, 149-151. Dostosujcie też zawartość app.json

**Comment by Marucik** [comment]
Ok, "skopiowałem" ustawienia z projektu który Pan podesłał, ale Heroku dalej nie pobiera staticfiles'ów

**Comment by xinulsw** [comment]
Po przetestowaniu wielu konfiguracji znalazłem kilka rzeczy do poprawy: 1) katalog static w katalogu projektu to nie jest domyślna lokalizacja, przeniosłem to do home/static/home; 2) z poprzedniego wynika konieczność aktualizacji szablonów oraz dest w gulp.js; 3) zmieniłem settings.py, żeby whitenoise wykorzystywać lokalnie i na heroku; 4) ale co najważniejsze usunąłem ignorowanie css – to było podstawowym źródłem problemów; 5) czas najwyższy scalić dev z master, heroku nie robi domyślnie deployingu dla gałęzi. [Udane wdrożenie »»»](https://obscure-mesa-16693.herokuapp.com/). Przygotuję pull reqest. Lokalnie trzeba doinstalować whitenoise.

**Comment by Marucik** [comment]
Zamykam i bierzemy się za analizę zmian 😀.
