### ISSUE TITLE
Oznaczanie aktywnych zakładek w menu.

### ISSUE THREAD

**Issue by Marucik** [Marucik/Ulatwiaczek#5]
To jak 
```
<head>
    :
    <style>
    #{% pageName %}{
    border-left: ...;
    }
    </style>
</head>
```
I dodajemy `id` do każdego elementu listy, czy jak?

**Comment by Dawiducik** [comment]
Więc tak, dodaj `id` do każdego elementu, podczas renderowania templatki na poziomie widoku doda się zmienną z nazwą tego widoku, do `base.html ` pasuje dodać blok o nazwie customStyles, więc `base.html `będzie wyglądać tak:
```
<style>
{% block customStyles %} {% endblock %}
</style>
```
Następnie już w templejtach odpowiadających za daną strone na górze kodu umieścimy nazwę widoku, który przekazywaliśmy jako parametr przy renderowaniu templejtu więc całość będzie wyglądać tak:
```
{% block customStyles %} 
#{{ pageName }} {
  border-left: 'xDD';
}
{% endblock %}
```

**Comment by Marucik** [comment]
Kitara

**Comment by Dawiducik** [comment]
```javascript
var i = 5;
```
