### ISSUE TITLE
Aplikacja nie zawiera żadnej obsługi użytkowników

### ISSUE THREAD

**Issue by xinulsw** [Marucik/Ulatwiaczek#8]
Sugeruję, żeby w pierwszym rzędzie dodać obsługę użytkowników, przecież nauczyciele czy uczniowie muszą się do systemu logować. Można użyć django-registration wg naszego [scenariusza](http://django-maly-bar.readthedocs.io/en/latest/malybar/index.html#uzytkownicy).

**Comment by Marucik** [comment]
Dodano obsługę użytkownika w tym [commicie](https://github.com/Marucik/Ulatwiaczek/commit/feb74587c25d5c2d522fcd90dc807b3545a4fa77). Zamykam.
