### ISSUE TITLE
Nazwa aplikacji

### ISSUE THREAD

**Issue by xinulsw** [Marucik/Ulatwiaczek#9]
Nazwy projektu i aplikacji "app" i "main" nie mówią nic o przeznaczeniu projektu. Proponuję jeszcze raz utworzyć projekt, np. "sprawdziany", i aplikację,  np. "testy". Co prawda nie będzie to do końca zgodne z zasadą, że aplikacja powinna realizować jedno zadanie, ale przy założeniu, że aplikacja nie będzie nadmiernie skomplikowana, można to zaakceptować. Więcej informacji o [projekcie i aplikacji »»»](https://docs.djangoproject.com/pl/1.10/ref/applications/#projects-and-applications)

**Comment by Marucik** [comment]
Poprawione w tym [commicie](https://github.com/Marucik/Ulatwiaczek/commit/1db96756f9c537273679a5121191121586f34e69).
